/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.8.2/samples
 */
plugins {
    war
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("jakarta.platform:jakarta.jakartaee-api:8.0.0")
}

java {
    version = JavaVersion.VERSION_11
}

tasks.create<Copy>("deploy") {
    dependsOn("build")
    from("$buildDir/libs")
    into("/usr/local/opt/preview-server/standalone/deployments")
}




