name: Build project
on: push

jobs:
    build:
      name: Build project
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Setup Java
          uses: actions/setup-java@v1
        - name: build
          run: ./gradlew check


